# Generated by Django 3.0.2 on 2020-08-08 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=4000)),
                ('message', models.CharField(max_length=4000)),
                ('is_definition', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FilesProcessed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='TrimmerEntry',
            fields=[
                ('sample_name', models.CharField(max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mabid', models.CharField(default='', max_length=50)),
                ('show_on_web', models.BooleanField(default=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('protein_target', models.CharField(blank=True, max_length=100, null=True)),
                ('light_count', models.IntegerField(blank=True, null=True)),
                ('heavy_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrimmerSequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SMARTindex', models.CharField(max_length=20)),
                ('pct_support', models.DecimalField(decimal_places=5, max_digits=10)),
                ('asv_support', models.DecimalField(decimal_places=5, max_digits=10)),
                ('total_reads', models.IntegerField()),
                ('seq_platform', models.CharField(choices=[('Illumina', 'Illumina'), ('Sanger', 'Sanger')], max_length=10)),
                ('plate', models.CharField(max_length=30)),
                ('seq', models.CharField(default='', max_length=1500)),
                ('e_value', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seq_start_index', models.IntegerField(blank=True, null=True)),
                ('seq_stop_index', models.IntegerField(blank=True, null=True)),
                ('scheme', models.CharField(blank=True, max_length=30, null=True)),
                ('frame', models.IntegerField(blank=True, null=True)),
                ('aa', models.CharField(blank=True, max_length=1000, null=True)),
                ('numbering', models.CharField(blank=True, max_length=3000, null=True)),
                ('domain', models.CharField(blank=True, max_length=1000, null=True)),
                ('duplicate', models.BooleanField(default=False)),
                ('sample_name', models.CharField(default='', max_length=20)),
                ('chain', models.CharField(choices=[('Light', 'Light'), ('Heavy', 'Heavy')], max_length=10)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence_db.TrimmerEntry')),
            ],
        ),
        migrations.CreateModel(
            name='TrimmerEntryStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_name', models.CharField(max_length=20)),
                ('plate_location', models.CharField(max_length=5)),
                ('volume', models.IntegerField(default=0)),
                ('concentration', models.IntegerField(default=0)),
                ('comments', models.CharField(max_length=50)),
                ('amplicon_concentration', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('failure', models.CharField(max_length=30)),
                ('inline_index_name', models.CharField(max_length=30)),
                ('inline_index', models.CharField(max_length=30)),
                ('LCs_reported', models.IntegerField(default=0)),
                ('HCs_reported', models.IntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence_db.TrimmerEntry')),
            ],
        ),
    ]
