# Generated by Django 3.0.2 on 2020-04-10 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(blank=True, default='', max_length=25)),
                ('target', models.CharField(blank=True, default='', max_length=50)),
                ('accession', models.CharField(blank=True, default='', max_length=20)),
                ('gene_name', models.CharField(blank=True, default='', max_length=20)),
                ('file_name', models.CharField(blank=True, default='', max_length=25)),
                ('iso_type', models.CharField(blank=True, default='', max_length=15)),
                ('validation_t', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('ND', 'ND'), ('Fail', 'Fail')], max_length=10)),
                ('validation_brib', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('ND', 'ND'), ('Fail', 'Fail')], max_length=10)),
                ('validation_brihc', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('ND', 'ND'), ('Fail', 'Fail')], max_length=10)),
                ('validation_ko', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('ND', 'ND'), ('Fail', 'Fail')], max_length=10)),
                ('tcsupe', models.CharField(blank=True, default='', max_length=25)),
                ('pure', models.CharField(blank=True, default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TrimmerEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mabid', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VHSeq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seq', models.CharField(default='', max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='VLSeq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seq', models.CharField(default='', max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='TrimmerLight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SMARTindex', models.CharField(max_length=20)),
                ('pct_support', models.DecimalField(decimal_places=5, max_digits=10)),
                ('asv_support', models.DecimalField(decimal_places=5, max_digits=10)),
                ('total_reads', models.IntegerField()),
                ('seq_platform', models.CharField(choices=[('Illumina', 'Illumina'), ('Sanger', 'Sanger')], max_length=10)),
                ('plate', models.CharField(max_length=30)),
                ('seq', models.CharField(default='', max_length=1500)),
                ('e_value', models.CharField(max_length=10)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seq_start_index', models.IntegerField()),
                ('seq_stop_index', models.IntegerField()),
                ('scheme', models.CharField(max_length=30)),
                ('frame', models.IntegerField()),
                ('aa', models.CharField(max_length=1000)),
                ('numbering', models.CharField(max_length=3000)),
                ('domain', models.CharField(max_length=1000)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence_db.TrimmerEntry')),
            ],
        ),
        migrations.CreateModel(
            name='TrimmerHeavy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SMARTindex', models.CharField(max_length=20)),
                ('pct_support', models.DecimalField(decimal_places=5, max_digits=10)),
                ('asv_support', models.DecimalField(decimal_places=5, max_digits=10)),
                ('total_reads', models.IntegerField()),
                ('seq_platform', models.CharField(choices=[('Illumina', 'Illumina'), ('Sanger', 'Sanger')], max_length=10)),
                ('plate', models.CharField(max_length=30)),
                ('seq', models.CharField(default='', max_length=1500)),
                ('e_value', models.CharField(max_length=10)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seq_start_index', models.IntegerField()),
                ('seq_stop_index', models.IntegerField()),
                ('scheme', models.CharField(max_length=30)),
                ('frame', models.IntegerField()),
                ('aa', models.CharField(max_length=1000)),
                ('numbering', models.CharField(max_length=3000)),
                ('domain', models.CharField(max_length=1000)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence_db.TrimmerEntry')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('metadata', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_db.Metadata')),
                ('vhseq', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_db.VHSeq')),
                ('vlseq', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_db.VLSeq')),
            ],
        ),
    ]
