# Generated by Django 3.0.2 on 2020-01-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VRSeq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seq', models.CharField(default='', max_length=1500)),
                ('entry', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_db.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='VLSeq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seq', models.CharField(default='', max_length=1500)),
                ('entry', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_db.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_db.Entry')),
            ],
        ),
    ]
