# Generated by Django 3.0.2 on 2020-08-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimmersequence',
            name='asv_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
