# Generated by Django 3.0.2 on 2020-01-27 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='vlseq',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='vrseq',
            name='entry',
        ),
        migrations.AddField(
            model_name='entry',
            name='metadata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_db.Metadata'),
        ),
        migrations.AddField(
            model_name='entry',
            name='vlseq',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_db.VLSeq'),
        ),
        migrations.AddField(
            model_name='entry',
            name='vrseq',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_db.VRSeq'),
        ),
    ]
