# Generated by Django 3.0.2 on 2020-04-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimmerheavy',
            name='e_value',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
