# Generated by Django 3.0.2 on 2020-02-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0002_auto_20200127_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='accession',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='metadata',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='metadata',
            name='gene_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='metadata',
            name='iso_type',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='metadata',
            name='pure',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='metadata',
            name='target',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='metadata',
            name='target_type',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='metadata',
            name='tcsupe',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='metadata',
            name='validation_brib',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('ND', 'ND'), ('Fail', 'Fail')], max_length=10),
        ),
        migrations.AddField(
            model_name='metadata',
            name='validation_brihc',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('ND', 'ND'), ('Fail', 'Fail')], max_length=10),
        ),
        migrations.AddField(
            model_name='metadata',
            name='validation_ko',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('ND', 'ND'), ('Fail', 'Fail')], max_length=10),
        ),
        migrations.AddField(
            model_name='metadata',
            name='validation_t',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('ND', 'ND'), ('Fail', 'Fail')], max_length=10),
        ),
    ]
