# Generated by Django 3.0.2 on 2020-04-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0002_auto_20200411_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimmerheavy',
            name='aa',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='trimmerheavy',
            name='domain',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='trimmerheavy',
            name='frame',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trimmerheavy',
            name='numbering',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='trimmerheavy',
            name='scheme',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trimmerheavy',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trimmerheavy',
            name='seq_start_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trimmerheavy',
            name='seq_stop_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trimmerlight',
            name='aa',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='trimmerlight',
            name='domain',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='trimmerlight',
            name='e_value',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trimmerlight',
            name='frame',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trimmerlight',
            name='numbering',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='trimmerlight',
            name='scheme',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trimmerlight',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trimmerlight',
            name='seq_start_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trimmerlight',
            name='seq_stop_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
