# Generated by Django 3.0.2 on 2020-11-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0002_trimmersequence_asv_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimmersequence',
            name='chain_id',
            field=models.CharField(default='', max_length=25),
        ),
    ]
