# Generated by Django 3.0.2 on 2020-02-05 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0003_auto_20200204_2304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VRSeq',
            new_name='VHSeq',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='vrseq',
            new_name='vhseq',
        ),
    ]
