# Generated by Django 3.0.2 on 2020-11-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0003_trimmersequence_chain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimmerentry',
            name='show_on_web',
            field=models.BooleanField(default=False),
        ),
    ]
