# Generated by Django 3.0.2 on 2020-04-11 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0003_auto_20200411_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrimmerEntryStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_name', models.CharField(max_length=20)),
                ('plate_location', models.CharField(max_length=5)),
                ('volumne', models.IntegerField()),
                ('concentration', models.IntegerField()),
                ('comments', models.CharField(max_length=50)),
                ('amplicon_concentration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('failure', models.CharField(max_length=30)),
                ('inline_index_name', models.CharField(max_length=30)),
                ('inline_index', models.CharField(max_length=30)),
                ('LCs_reported', models.IntegerField()),
                ('HCs_reported', models.IntegerField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence_db.TrimmerEntry')),
            ],
        ),
    ]
