# Generated by Django 3.0.2 on 2022-08-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0004_auto_20201112_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimmerentry',
            name='clonality',
            field=models.CharField(choices=[('Monoclonal', 'Monoclonal'), ('Oligoclonal', 'Oligoclonal')], default='', max_length=12),
        ),
    ]
