# Generated by Django 3.0.2 on 2020-03-22 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0004_auto_20200205_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrimmerEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trimmerid', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrimmerLight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pctsupport', models.DecimalField(decimal_places=5, max_digits=10)),
                ('asvcount', models.IntegerField()),
                ('plate', models.CharField(max_length=15)),
                ('SMARTindex', models.CharField(max_length=20)),
                ('seq', models.CharField(default='', max_length=1500)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence_db.TrimmerEntry')),
            ],
        ),
        migrations.CreateModel(
            name='TrimmerHeavy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pctsupport', models.DecimalField(decimal_places=5, max_digits=10)),
                ('asvcount', models.IntegerField()),
                ('plate', models.CharField(max_length=15)),
                ('SMARTindex', models.CharField(max_length=20)),
                ('seq', models.CharField(default='', max_length=1500)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence_db.TrimmerEntry')),
            ],
        ),
    ]
