# Generated by Django 3.0.2 on 2020-04-11 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0004_trimmerentrystatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trimmerentrystatus',
            old_name='volumne',
            new_name='volume',
        ),
    ]
