# Generated by Django 4.1.1 on 2023-03-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0005_trimmerentry_clonality'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimmersequence',
            name='anarci_bad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trimmersequence',
            name='anarci_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trimmersequence',
            name='subseqs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
