# Generated by Django 3.0.2 on 2020-04-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0005_auto_20200411_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimmerheavy',
            name='duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trimmerlight',
            name='duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
