# Generated by Django 3.0.2 on 2020-05-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0006_auto_20200415_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='trimmerentry',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trimmerentry',
            name='protein_target',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trimmerentry',
            name='show_on_web',
            field=models.BooleanField(default=True),
        ),
    ]
