# Generated by Django 4.1.1 on 2023-05-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0007_trimmersequence_bad_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimmersequence',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
