# Generated by Django 3.0.2 on 2020-05-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0007_auto_20200510_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimmerheavy',
            name='sample_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trimmerlight',
            name='sample_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
