# Generated by Django 4.1.1 on 2023-05-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0008_trimmersequence_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimmerentry',
            name='max_hcstars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trimmerentry',
            name='max_lcstars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
