# Generated by Django 3.0.2 on 2020-06-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0008_auto_20200526_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimmerentrystatus',
            name='HCs_reported',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trimmerentrystatus',
            name='LCs_reported',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trimmerentrystatus',
            name='amplicon_concentration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trimmerentrystatus',
            name='concentration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trimmerentrystatus',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
