# Generated by Django 4.1.1 on 2023-05-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0009_trimmerentry_max_hcstars_trimmerentry_max_lcstars'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimmerentry',
            name='maxavgstars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
