# Generated by Django 3.0.2 on 2020-06-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0009_auto_20200610_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimmerentry',
            name='mabid',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
