# Generated by Django 3.0.2 on 2020-06-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0010_auto_20200618_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimmerentry',
            name='mabid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
