# Generated by Django 4.1.1 on 2023-05-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0010_trimmerentry_maxavgstars'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimmersequence',
            name='asv_stars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trimmersequence',
            name='duplicate_stars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
