# Generated by Django 3.0.2 on 2020-06-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0011_auto_20200622_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('someAttr', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='trimmerentry',
            name='heavy_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trimmerentry',
            name='light_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
