# Generated by Django 4.1.1 on 2023-08-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0011_trimmersequence_asv_stars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimmersequence',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
