# Generated by Django 4.1.1 on 2023-08-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0012_trimmersequence_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimmerentry',
            name='contains_verified',
            field=models.BooleanField(default=False),
        ),
    ]
