# Generated by Django 3.0.2 on 2020-06-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0012_auto_20200626_0202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
