# Generated by Django 4.1.1 on 2023-09-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0013_trimmerentry_contains_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimmerentry',
            name='contains_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trimmersequence',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
