# Generated by Django 3.0.2 on 2020-07-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0014_filesprocessed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=4000)),
                ('message', models.CharField(max_length=4000)),
            ],
        ),
    ]
