# Generated by Django 4.1.1 on 2023-09-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_db', '0014_trimmerentry_contains_failed_trimmersequence_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimmerentry',
            name='scfv_verified',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
